# Generated by Django 2.1.3 on 2018-11-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reccommendAlba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='User Name')),
                ('birth_date', models.CharField(max_length=10, verbose_name='Birth Date')),
                ('type_EI', models.CharField(max_length=5, verbose_name='E or I')),
                ('type_SN', models.CharField(max_length=5, verbose_name='S or N')),
                ('type_TF', models.CharField(max_length=5, verbose_name='T or F')),
                ('type_JP', models.CharField(max_length=5, verbose_name='J or P')),
            ],
        ),
    ]
