# Generated by Django 2.1.3 on 2018-11-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reccommendAlba', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Female', max_length=20, verbose_name='User Gender'),
        ),
    ]
