# Generated by Django 2.1.3 on 2018-11-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reccommendAlba', '0003_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('gender_preference', models.CharField(max_length=40, verbose_name='Gender Preference')),
                ('payment', models.CharField(max_length=40, verbose_name='Payment')),
                ('work_type', models.CharField(max_length=100, verbose_name='Work Type')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('url_link', models.CharField(max_length=100, verbose_name='Url Link')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='female', max_length=20, verbose_name='User Gender'),
        ),
    ]
